# Generated by Django 4.1.5 on 2023-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrar",
            name="about",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
