# Generated by Django 4.1.5 on 2023-02-26 16:21

from django.db import migrations, models
import registrar_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("NOC", "NOC-Application"),
                            ("SM", "Seminar-Application"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "upload_file",
                    models.FileField(upload_to=registrar_app.models.upload_to),
                ),
                ("remarks", models.TextField(blank=True)),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
