# Generated by Django 4.1.5 on 2023-03-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0006_remove_registrar_applications"),
        ("registrar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="registrar",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="accounts_app.registrar",
            ),
            preserve_default=False,
        ),
    ]
